FROM python:3.9-slim

WORKDIR /app

COPY main.py .
COPY requirements.txt .

# Install curl for healthcheck and git for huggingface
RUN apt-get update && \
    apt-get install -y curl git && \
    apt-get clean

RUN pip3 install --no-cache-dir -r requirements.txt

# Set environment variables
ENV PYTHONUNBUFFERED=1

# Expose the port that the FastAPI app will run on
EXPOSE 8000

# Command to run the FastAPI application
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]