FROM python:3.9-slim

COPY streamlit_ui.py .
COPY requirements-ui.txt .

RUN pip3 install --upgrade pip
RUN pip3 install --no-cache-dir -r requirements-ui.txt

# Set environment variables
ENV PYTHONUNBUFFERED=1

# Expose the port that Streamlit runs on
EXPOSE 8501

# Command to run the Streamlit application
CMD ["streamlit", "run", "streamlit_ui.py", "--server.port=8501", "--server.address=0.0.0.0"]